### ISSUE TITLE
Long literal

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#10]
Exercise 3.22. Modify the Parser to parse and return nodes for the long literal.

**Comment by tjsg1992** [comment]
See https://github.com/tjsg1992/j--/commit/913f00f9b94cd4e579c8415c3812eea85730846f for how this was done with doubles and floats. Ignore the changes to Type.java

**Comment by cresse** [comment]
Alright, I'll snap this up then

**Comment by cresse** [comment]
alright copied and pasted *wipes sweat from brow* phew

**Comment by tjsg1992** [comment]
Branch has been merged and this issue is now in the same state as the floats/literals issue.

**Comment by tjsg1992** [comment]
Cleared!
