### ISSUE TITLE
All additional operators

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#11]
Exercise 3.23. Modify the Parser to parse and return nodes for all the additional operators
that are defined in Java but not yet in j--.

**Comment by tjsg1992** [comment]
For reference, operator expression nodes used in Parser, like JMultiplyOp, are located as default inner classes located within JBinaryExpression. Other operators can be found in JUnaryExpression.

What's a package, again?

**Comment by cresse** [comment]
working on this in pt2-operators. i figure 'operators' isn't quite descriptive enough so i'll be using pt# as a prefix to every branch to provide some extra (probably unnecessary) detail

**Comment by cresse** [comment]
so according to [this](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html) we've got these to implement. of these, + - * are done already
++ -- postfix
++ -- + - ~ ! unary
* / % multiplicative
+ - additive
<< >> >>> shift
> < >= <= instanceof
== != equality
& bit and
^ bit xor
| bit or
&& logical and
|| logical or
? : ternary
= += -= *= &= ^= |= <<= >>= >>>= assignment

**Comment by cresse** [comment]
I also noticed that there were constants being pulled from CLConstants in the jminusminus folder.

IDIV is integer division, which is separate from LDIV or FDIV, naturally. so the + - * that are already in aren't actually done for floats and doubles.

**Comment by cresse** [comment]
alright for my sanity and probably your guys' too, [here](https://github.com/tjsg1992/j--/blob/master/src/jminusminus/CLConstants.java#L498) is where all the ops seem to start. I really don't think we're meant to make our own additions here but if we are then Shit

**Comment by tjsg1992** [comment]
I'm checking now, but I think most of the CL stuff is used for codegen only.
Also! If you ever need to do weird formatting stuff on Github, doing so in their code tags would probably work.

**Comment by tjsg1992** [comment]
Yeah, the constants you were using were within codegen methods, which is probably not going to be a factor until the final stages of the product.

**Comment by tjsg1992** [comment]
Okay, so all new operators have been added to JBinaryExpression and JUnaryExpression. These are the nodes that will be created and added to the AST. For now, 

However, we still need to add these variables to Parser so that the operator tokens are correctly parsed and that their corresponding nodes are created. [This appears to begin here.](https://github.com/tjsg1992/j--/blob/master/src/jminusminus/Parser.java#L999)

**Comment by tjsg1992** [comment]
Added in Parser support for all operators EXCEPT:
shift
bitwise AND
bitwise exclusive OR
bitwise inclusive OR
logical OR
ternary [later]

However, method placeholders for these operators have been inserted. The positions of these in the code are deliberate in order to follow the Java operator precedence levels. Note that we are going to have to edit previously-written expression parsers to include these new ones. For instance, conditionalAndExpressions consider their left and right hand sides to be equality expressions. They should actually consider them to be bitwiseOrExpressions first.

**Comment by tjsg1992** [comment]
Well that was nightmarish. Pull request open.

**Comment by tjsg1992** [comment]
Closing issue for now.
