### ISSUE TITLE
Conditional expressions

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#12]
Exercise 3.24. Modify the Parser to parse and return nodes for conditional expressions, for
example, (a > b) ? a : b.

**Comment by tjsg1992** [comment]
Conditional expression does not include the if statement, which is already part of j-- anyway.

**Comment by VRushLP** [comment]
This should be working, but I'm having difficulty testing on my machine.
What happens is when the parser detects a ? operator as part of the assignment expression call, it calls ternaryAssignment, which must find a colon as part of it's parsing. If it finds one, it returns a new JTernaryExpression object, of which two of it's constructor arguments are calls to assignmentExpression.

**Comment by tjsg1992** [comment]
Updated, tested, and added to grammar.
