### ISSUE TITLE
Throw statement

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#16]
Exercise 3.28. Modify the Parser to parse and return nodes for the throw-statement.

**Comment by tjsg1992** [comment]
Parsing will start within Parser.statement() [line 640]

**Comment by cresse** [comment]
Current state: Parser is modified and JThrowsStatement is in. Compiles fine, but fails to build if "throws" is found before the { in a test class - specifically, { is expected and throws is found.
Not quite sure how to proceed since error reporting isn't very helpful when building.

**Comment by tjsg1992** [comment]
Right on, we might be able to work it out today after class. I'm also on campus in SCI 108 and will be until class (except for lunch at noon!) if you wanted to work on it together for a bit.

**Comment by tjsg1992** [comment]
Add an else if clause for THROW inside of statement. Check for have(NEW) and call creator() and set the output to a JExpression. Otherwise set the next part to be an identifier.

Create a JThrowStatement class with two constructors, one that takes a constructor (e.g. throw new Exception) and one that takes an identifier (e.g. throw e). Then setup output accordingly.

**Comment by tjsg1992** [comment]
JThrowsStatement:

tryStatement

Array of catch identifiers & catchStatements

finallyStatement

**Comment by cresse** [comment]
this is done!
