### ISSUE TITLE
4.1 Public Type Declarations

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#37]
Exercise 4.1. The compiler does not enforce the Java rule that only one type declaration
(that is, class declaration in j--) be declared public. Repair this in one of the analyze()
methods.

**Comment by tjsg1992** [comment]
I think this is stating that you could do something like:

public class myClass() {
   ...
}

public class myOtherClass() {
   ...
}

In the same class file, which apparently isn't legal. The other class would need to be any type besides public.

**Comment by cresse** [comment]
We want to work with analyze() in JClassDeclaration, line 198.

**Comment by tjsg1992** [comment]
As a note, I just tested, and as we originally thought, having two separate public classes in the same class file is illegal.
But what's interesting is that a public class can have an inner public class. So keep in mind that we won't need to check for that.

**Comment by tjsg1992** [comment]
The two allowed modifiers for a separate second class are final, abstract, and default (e.g. no modifiers)

**Comment by tjsg1992** [comment]
I think I may know what to do. Give me a bit of mutex for the next hour.

**Comment by tjsg1992** [comment]
Done. Make sure you change the options flag from -p to -a when running.
