### ISSUE TITLE
4.2 Changes to Type.ANY

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/j--#38]
The analyze() method in JVariable assigns the type Type.ANY to a
JVariable (for example, x) in the AST that has not been declared in the symbol table.
This prevents a cascading of multiple errors from the report of a single undeclared variable.
But we could go further by declaring the variable (as Type.ANY) in the symbol table so
as to suppress superfluous error reports in subsequent encounters of the variable. Make this
improvement to analysis.

**Comment by cresse** [comment]
analyze() in JVar is line 66

**Comment by cresse** [comment]
context.java, line 84 is where the symbol table seems to be

**Comment by tjsg1992** [comment]
Done.
